### ISSUE TITLE
Wywalić do funkcji 

### ISSUE THREAD

**Issue by not7cd** [ekaterinatrofa/ZTM4People#2]
https://github.com/ekaterinatrofa/ZTM4People/blob/08398840c49b2a8dafabf098ed4c50d3e0ca1ffc/ZTM/views.py#L6-L9

Coś tam coś tam MVC

**Comment by Sequindo** [comment]
Hi @not7cd,
The code has been refactored so Django is no longer used. This is now a simple client-side app using Javascript.

**Comment by not7cd** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEE
